### ISSUE TITLE
The command '"npm" "run" "build"' failed with exit status 'exit code: 1'

### ISSUE THREAD

**Issue by CFWHISPERER** [MioQuispe/create-ic-app#11]
Thanks for the work you are doing, we are trying to get a successful "svelte" Javascript install on Ubuntu 20.04 dfx version 0.8.1 and on running "dfx deploy" we are hitting the following messages...

The post-build step failed for canister 'rrkah-fqaaa-aaaaa-aaaaq-cai' with an embedded error: The command '"npm" "run" "build"' failed with exit status 'exit code: 1'.
Stdout:

> svelte-version@0.0.0 build
> vite build

Stderr:
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'worker_threads'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/mikebrunt/create-ic-app-main_2/create_ic_app/svelte-version/node_modules/vite/dist/node/chunks/dep-55830a1a.js:14:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by MioQuispe** [comment]
Yep managed to run it locally without issues. Try upgrading and let me know how it went.
